### PR TITLE
Feature/develop/task3

### PR DESCRIPTION
**Pull request by Bozhyk-Oleh**
lab 3-4

### CODE REVIEW

**Comment by andrii-s-shpitser-lpnu-ua** [comment]
please add test run during action runing

**Review by andrii-s-shpitser-lpnu-ua — APPROVED** [review]

**Comment by Bozhyk-Oleh** [comment]
edit connection string in App.config

**Comment by andrii-s-shpitser-lpnu-ua** [comment]
> edit connection string in App.config

but your format is JSON, not XML. You should reate JSON config file for this

**Comment by Bozhyk-Oleh** [comment]
> u
added important.json with connection string

**Review by andrii-s-shpitser-lpnu-ua — APPROVED** [review]

**Pull request merged**
